Packages update

diff --git a/feeds/packages/net/ndyndns/files/ndyndns.init b/feeds/packages/net/ndyndns/files/ndyndns.init
--- a/feeds/packages/net/ndyndns/files/ndyndns.init
+++ b/feeds/packages/net/ndyndns/files/ndyndns.init
@@ -1,18 +1,21 @@
 #!/bin/sh /etc/rc.common
-# Copyright (C) 2007 OpenWrt.org
+# Copyright (C) 2007-2012 OpenWrt.org
 
 START=80
-DEFAULT=/etc/default/ndyndns
 
 start() {
-	[ -f $DEFAULT ] && . $DEFAULT
+	. /lib/functions/network.sh
 
-	. /etc/functions.sh
-	include /lib/network
-	scan_interfaces
-	/usr/sbin/ndyndns -c $CHROOT -f $CONFIG -i $(config_get wan ifname) $OPTIONS
+	[ -f /etc/ndyndns/ndyndns.conf ] || {
+		echo "$0: missing config file '/etc/ndyndns/ndyndns.conf'" 1>&2
+		return 1
+	}
+
+	local device
+	network_get_device device wan && \
+		service_start /usr/sbin/ndyndns -c /etc/ndyndns -f /etc/ndyndns/ndyndns.conf -i $device
 }
 
 stop() {
-	killall ndyndns
+	service_stop /usr/sbin/ndyndns
 }
